### ISSUE TITLE
Error is shown when building in XCode for Simulator on a Mac with the Apple M1 chip

### ISSUE THREAD

**Issue by akoshkidko** [andyfinnell/NativeMarkKit#16]
Hello, @andyfinnell 

The following error is shown when building for Simulator on my MacBook with the Apple M1 chip:

Could not find module 'NativeMarkKit' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /Users/aleksej/Library/Developer/Xcode/DerivedData/iosApp-glchnlwfebmjiydqhggiurekbzue/Build/Products/phoenixDebug-iphonesimulator/NativeMarkKit.swiftmodule

Can you advice please how to fix that? Or should it be fixed inside the library itself?

Thanks.

**Comment by andyfinnell** [comment]
Hey, sorry you're having problems with this. I don't have access to an M1 Mac, so I'm not able to try to reproduce.

I do notice it's looking for an x86 binary for the simulator, which sounds unexpected to me given you're running on an M1. I would expect it to look for the ARM simulator binary (which does appear to be there). Maybe there something in the containing project that's still trying to build x86?

**Comment by akoshkidko** [comment]
>I do notice it's looking for an x86 binary for the simulator, which sounds unexpected to me given you're running on an M1

Yes, it's also strange for me, so might it be because library doesn't not support ARM64 and cannot be built for M1 arch? Could you check please that arm architecture is supported by your lib so it's possible to use on a Mac with M1?

I tried to build it on my old MacBook with Intel Chip and it works fine. Also it works on my MacBook with M1 chip if I use "Open using Rosetta mode"

**Comment by andyfinnell** [comment]
Arm is definitely supported on iOS. The error message you're getting in part says:

> found: arm64, arm64-apple-ios-simulator,

which sounds like ARM is being built for the simulator. I think the containing app is looking for an x86 for some reason (see the error message `Could not find module 'NativeMarkKit' for target 'x86_64-apple-ios-simulator'`). It sounds like NativeMarkKit _is_ being built for ARM on the Simulator, but the containing app wants x86 on the Simulator.

**Comment by akoshkidko** [comment]
@andyfinnell seems that's really because of our containing project settings. Thank you very much for your help!
